#!/bin/bash
set -euo pipefail

# Sync Terraform configuration from SSM Parameter Store
# This ensures terraform.tfvars matches the infrastructure for the specified environment
#
# Usage: ./scripts/sync-terraform-config.sh <dev|prod>
#
# The values stored in SSM are the source of truth for Terraform configuration.
# This prevents the "missing tfvars" problem where developers accidentally
# apply Terraform with default values against the wrong environment.
#
# SSM Parameters (per environment):
#   /ship/terraform-config/{env}/environment        - Required: "dev" or "prod"
#   /ship/terraform-config/{env}/app_domain_name    - Optional: custom domain
#   /ship/terraform-config/{env}/route53_zone_id    - Optional: for DNS records
#   /ship/terraform-config/{env}/eb_environment_cname - Optional: EB CNAME
#
# To set up a new environment, create the SSM parameters first:
#   aws ssm put-parameter --name /ship/terraform-config/environment --value prod --type String
#   aws ssm put-parameter --name /ship/terraform-config/dev/environment --value dev --type String
#   aws ssm put-parameter --name /ship/terraform-config/shadow/environment --value shadow --type String
#
# IMPORTANT: Do not hardcode values in terraform.tfvars files. They are
# auto-generated from SSM and will be overwritten on next sync.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Parse environment argument
ENV="${1:-}"
if [[ ! "$ENV" =~ ^(dev|shadow|prod)$ ]]; then
  echo "Usage: $0 <dev|shadow|prod>"
  echo ""
  echo "Examples:"
  echo "  $0 dev     # Sync dev environment config"
  echo "  $0 shadow  # Sync shadow environment config (UAT)"
  echo "  $0 prod    # Sync prod environment config"
  exit 1
fi

# Environment-specific paths
# - prod uses existing terraform at root with original SSM path
# - dev/shadow use new modular structure
if [ "$ENV" = "prod" ]; then
  TFVARS_FILE="$PROJECT_ROOT/terraform/terraform.tfvars"
  SSM_PREFIX="/ship/terraform-config"
else
  # dev and shadow both use the modular terraform structure
  TFVARS_FILE="$PROJECT_ROOT/terraform/environments/$ENV/terraform.tfvars"
  SSM_PREFIX="/ship/terraform-config/$ENV"
fi

echo "Syncing Terraform config for $ENV environment from SSM..."

# Fetch all terraform-config parameters for this environment
ENVIRONMENT=$(aws ssm get-parameter --name "$SSM_PREFIX/environment" --query 'Parameter.Value' --output text 2>/dev/null || echo "")
APP_DOMAIN_NAME=$(aws ssm get-parameter --name "$SSM_PREFIX/app_domain_name" --query 'Parameter.Value' --output text 2>/dev/null || echo "")
ROUTE53_ZONE_ID=$(aws ssm get-parameter --name "$SSM_PREFIX/route53_zone_id" --query 'Parameter.Value' --output text 2>/dev/null || echo "")
EB_ENVIRONMENT_CNAME=$(aws ssm get-parameter --name "$SSM_PREFIX/eb_environment_cname" --query 'Parameter.Value' --output text 2>/dev/null || echo "")

# Validate required values exist
if [ -z "$ENVIRONMENT" ]; then
  echo "ERROR: SSM parameter $SSM_PREFIX/environment not found"
  echo "Run 'aws ssm put-parameter --name $SSM_PREFIX/environment --value $ENV --type String' to create it"
  echo ""
  echo "Bootstrap examples:"
  echo "  prod:   aws ssm put-parameter --name /ship/terraform-config/environment --value prod --type String"
  echo "  dev:    aws ssm put-parameter --name /ship/terraform-config/dev/environment --value dev --type String"
  echo "  shadow: aws ssm put-parameter --name /ship/terraform-config/shadow/environment --value shadow --type String"
  exit 1
fi

# Generate terraform.tfvars
cat > "$TFVARS_FILE" << EOF
# Auto-generated from SSM Parameter Store
# Source: $SSM_PREFIX/*
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# DO NOT EDIT THIS FILE DIRECTLY
# Update the SSM parameters and re-run: ./scripts/sync-terraform-config.sh $ENV

environment = "$ENVIRONMENT"
EOF

# Add optional parameters if they exist
if [ -n "$APP_DOMAIN_NAME" ]; then
  echo "app_domain_name = \"$APP_DOMAIN_NAME\"" >> "$TFVARS_FILE"
fi

if [ -n "$ROUTE53_ZONE_ID" ]; then
  echo "route53_zone_id = \"$ROUTE53_ZONE_ID\"" >> "$TFVARS_FILE"
fi

if [ -n "$EB_ENVIRONMENT_CNAME" ]; then
  echo "eb_environment_cname = \"$EB_ENVIRONMENT_CNAME\"" >> "$TFVARS_FILE"
fi

echo ""
echo "Generated $TFVARS_FILE:"
echo "─────────────────────────────────────"
cat "$TFVARS_FILE"
echo "─────────────────────────────────────"
echo ""
echo "✓ Terraform config for $ENV synced from SSM"
